//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STAAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_User
    {
        public long ID { get; set; }
        public string Full_Name { get; set; }
        public string Password { get; set; }
        public Nullable<long> User_ID { get; set; }
        public Nullable<long> Role_ID { get; set; }
        public Nullable<long> Fingerprint_ID { get; set; }
    
        public virtual Fingerprint Fingerprint { get; set; }
        public virtual Role Role { get; set; }
        public virtual User User { get; set; }
    }
}
