//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STAAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customization
    {
        public int ID { get; set; }
        public string Company { get; set; }
        public string Company_Unique_ID { get; set; }
        public string Website { get; set; }
        public string Phone { get; set; }
        public string Sender_Email { get; set; }
        public string Sender_Email_Password { get; set; }
        public string Sender_Name { get; set; }
        public string Company_Contactless_Key { get; set; }
    }
}
