//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STAAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Configuration
    {
        public int ID { get; set; }
        public string Server { get; set; }
        public int Port { get; set; }
        public string DB_Name { get; set; }
        public string DB_User { get; set; }
        public string DB_Password { get; set; }
    }
}
