//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STAAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fingerprint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fingerprint()
        {
            this.Admin_User = new HashSet<Admin_User>();
        }
    
        public long ID { get; set; }
        public long User_ID { get; set; }
        public int Finger_ID { get; set; }
        public byte[] Picture { get; set; }
        public string Template { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admin_User> Admin_User { get; set; }
        public virtual Finger_Definition Finger_Definition { get; set; }
        public virtual User User { get; set; }
    }
}
