//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STAAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class License_Definition
    {
        public int ID { get; set; }
        public string Company { get; set; }
        public System.DateTime Begin { get; set; }
        public System.DateTime End { get; set; }
        public string Company_Unique_ID { get; set; }
        public string License_Key { get; set; }
        public string License_Type { get; set; }
        public string Device_Count { get; set; }
        public string User_Count { get; set; }
        public string Contactless_Key { get; set; }
    }
}
