//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STAAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movement
    {
        public long ID { get; set; }
        public long Reason_ID { get; set; }
        public long User_ID { get; set; }
        public string Location { get; set; }
        public System.DateTime Time_Out { get; set; }
        public Nullable<System.DateTime> Time_In { get; set; }
    
        public virtual Movement_Reason Movement_Reason { get; set; }
        public virtual User User { get; set; }
    }
}
